server:
  port: 8999
  
eureka:  instance:    hostname: localhost  
    

    
    
spring:  application:    name: api-gateway
    
  cloud:    gateway:      routes:
       
            - id: agent-server
        uri: lb://agent-server
        predicates:        - Path=/api/v1/**
        
      - id: client-server
        uri: lb://client-server
        predicates:        - Path=/client/api/v1/**
        
      - id: transaction-server
        uri: lb://transaction-server
        predicates:        - Path=/transaction/api/v1/**
        
      - id: auth-api
        uri: lb://auth-api
        predicates:
         - Path=/auth/api/**                      security:    user:      name: divakar
      password: verma
            roles:      - admin
      
      
      
                